export CUDA_VISIBLE_DEVICES=0

model_name=SDFormer

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --d_model 512 \
  --d_ff 2048 \
  --n_heads 4 \
  --dropout 0.1 \
  --batch_size 16 \
  --learning_rate 0.0001 \
  --train_epochs 20 \
  --patience 7 \
  --loss Huber \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --d_model 512 \
  --d_ff 2048 \
  --n_heads 4 \
  --dropout 0.1 \
  --batch_size 16 \
  --learning_rate 0.0001 \
  --train_epochs 20 \
  --patience 7 \
  --loss Huber \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --d_model 512 \
  --d_ff 2048 \
  --n_heads 4 \
  --dropout 0.1 \
  --batch_size 16 \
  --learning_rate 0.0001 \
  --train_epochs 20 \
  --patience 7 \
  --loss Huber \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --d_model 512 \
  --d_ff 2048 \
  --n_heads 4 \
  --dropout 0.1 \
  --batch_size 16 \
  --learning_rate 0.0001 \
  --train_epochs 20 \
  --patience 7 \
  --loss Huber \
  --patch_sizes 16,32,64 \
  --des 'Exp' \
  --itr 1
